### ISSUE TITLE
missing file: obj_writer.h?

### ISSUE THREAD

**Issue by jongmoochoi** [qianyizh/UrbanReconstruction#1]
Ln 8 in bpo2obj.cpp shows
#include "graphics/obj_writer.h"
but I cannot find it.

**Comment by qianyizh** [comment]
Thanks for pointing it out.

I have double checked.
``bpo2obj`` does not belong to the vanilla UrbanReconstruction project.
Someone added it and I accidentally included it in the repository.
It has some ancient dependencies so the compile error.
But it is not important. Just remove ``bpo2obj``.

The fix has been applied in #2
